### ISSUE TITLE
rdpi statistical comparison among groups

### ISSUE THREAD

**Issue by kmbecklin** [ameztegui/Plasticity#1] opened 2020-08-21 02:39 UTC
I am using the RDPI code to compare plasticity among multiple species. I have more than 2 groups to compare, but I keep getting the error message:

error in t.test.formula(RDPI$rdpi ~ RDPI$sp) : 
  grouping factor must have exactly 2 levels 

It appears that the program is not recognizing that it needs to use the ANOVA analysis rather than a t-test.

**Comment by ameztegui** [comment] 2020-08-21 08:06
Hi kmbecklin,
I am not sure why you are getting this error. Could you please verify that your "sp" variable is actually a factor and the number of levels? Or ideally, you could post a reproducible example so I can test the function's behavior.

Thanks!

**Comment by kmbecklin** [comment] 2020-08-21 11:26
I converted my “sp” data into a factor (using as.factor) with four levels and double checked the structure of the data set. I will send you a reproducible example shortly.

Thanks,
Katie

******************

Katie M. Becklin
Department of Biology
Syracuse University
442 Life Sciences Complex
107 College Place<x-apple-data-detectors://2/1>
Syracuse, NY 13244<x-apple-data-detectors://2/1>
(315) 443-2155
kmbeckli@syr.edu<mailto:kmbeckli@syr.edu>

On Aug 21, 2020, at 4:06 AM, Aitor Ameztegui <notifications@github.com> wrote:

﻿

Hi kmbecklin,
I am not sure why you are getting this error. Could you please verify that your "sp" variable is actually a factor and the number of factors? Or ideally, you could post a reproducible example so I can test the function's behavior.

Thanks!

**Comment by kmbecklin** [comment] 2020-08-21 11:54
Aitor,

Attached is a data file with one example of the data. This is the first time I’ve used the RDPI code, so I appreciate your help in diagnosing the problem.

t30 <- read.csv("tara30.csv")
View(t30)
dataframe <- as.data.frame(t30)
t30$CO2 <- as.factor(t30$CO2)
t30$sp <- as.factor(t30$sp)
str(t30)
rdpi(t30,sp,photo,CO2)

*******************
Katie M. Becklin
Assistant Professor
Biology Department
(pronouns: she, her, hers)
T 315.443.2155    F 315.443.2012
kmbeckli@syr.edu<mailto:kmbeckli@syr.edu>
107 College Place, LSC 442, Syracuse, NY 13244
thecollege.syr.edu/biology<http://thecollege.syr.edu/biology>
Syracuse University

**Comment by ameztegui** [comment] 2020-08-31 15:03
Hi  Katie,
sorry for the delayed answer, I was on holiday for 10 days. I still can't see any attachment. You should be able to upload it here, but if this doesn't work you may want to send it to ameztegui@gmail.com, and I will have a look as soon as possible.

Thank you!

**Comment by ameztegui** [comment] 2020-09-01 11:12
Hi again,
I think I may have found the reason for your error message, Somewhere in my code I forgot to ensure that the newly created object was a factor. Please try to install the package again and let me know if this solves your issue.

Best
Aitor

**Comment by kmbecklin** [comment] 2021-07-03 00:23
Aitor,

I have tried the Plasticity package multiple times since our last communication. I can generate a graph and I can correctly run the statistical comparison as long as the factor has only two levels. Every time I try a data set with 3+ factors, I get an error. Basically, the program is trying to run a t-test instead an ANOVA regardless of the number of levels.

I tried re-installing the package using the remotes::install_github("ameztegui/Plasticity") code listed on your github. It did not resolve the issue.

Given that the code is producing a graph, I expect that it is calculating RDPI correctly. However, I can’t seem to view, compare or summarize the calculated values. Any tips would be appreciated.

Cheers,
Katie


*******************
Katie M. Becklin
Assistant Professor
Biology Department
(pronouns: she, her, hers)
T 315.443.2155    F 315.443.2012
***@***.******@***.***>
107 College Place, LSC 442, Syracuse, NY 13244
thecollege.syr.edu/biology<http://thecollege.syr.edu/biology>
Syracuse University


From: Aitor Ameztegui ***@***.***>
Reply-To: ameztegui/Plasticity ***@***.***>
Date: Tuesday, September 1, 2020 at 5:12 AM
To: ameztegui/Plasticity ***@***.***>
Cc: Katie Becklin ***@***.***>, Author ***@***.***>
Subject: Re: [ameztegui/Plasticity] rdpi statistical comparison among groups (#1)


Hi again,
I think I may have found the reason for your error message, Somewhere in my code I forgot to ensure that the newly created object was a factor. Please try to install the package again and let me know if this solves your issue.

Best
Aitor

**Comment by ameztegui** [comment] 2021-07-09 15:47
Hi Katie,
sorry for my late reply. This is really weird, I have just checked and it correctly performs a t-test if my dataset has a two level factor, and an ANOVA otherwise. In your last messages you told me you were attaching an example dataset, but I was never able to see it.

As for the output of the function, if you just run the function it will give you a graph and the result of the statistical test. However, if you assign it to an object, it will create a dataframe with the pairwise differences for each level of the factor, allowing you to perform your own statistical test if you wish. 
`data(ecophysio)
rdpi(ecophysio,sp,SB, Piso)`
will produce the chart and print the result of the ANOVA, whereas

`result <- rdpi(ecophysio,sp,SB, Piso)`
will create the object `result`with the rdpi values.

I am sorry I cannot be of more help, but as I said, this works well for me with several different data frames, so I cannot tell where the problem comes from. You could try the example dataset I provide (run `data(ecophysio)`) and see if it works with the four levels (it should do an ANOVA), and if you remove two of the levels (then it should do a t-test). Let me know if this works as expected!

Cheers
Aitor

**Comment by kmbecklin** [comment] 2021-07-09 16:37
Thank you, Aitor.

There must be something off about how the program is loaded in my version of R, or how I’ve formatted the data. I will try the dataset you suggested and see if I can at least get it to reproduce the results.

Cheers,
Katie

******************

On Jul 9, 2021, at 9:47 AM, Aitor Ameztegui ***@***.***> wrote:

﻿

Hi Katie,
sorry for my late reply. This is really weird, I have just checked and it correctly performs a t-test if my dataset has a two level factor, and an ANOVA otherwise. In your last messages you told me you were attaching an example dataset, but I was never able to see it.

As for the output of the function, if you just run the function it will give you a graph and the result of the statistical test. However, if you assign it to an object, it will create a dataframe with the pairwise differences for each level of the factor, allowing you to perform your own statistical test if you wish.
data(ecophysio) rdpi(ecophysio,sp,SB, Piso)
will produce the chart and print the result of the ANOVA, whereas

result <- rdpi(ecophysio,sp,SB, Piso)
will create the object resultwith the rdpi values.

I am sorry I cannot be of more help, but as I said, this works well for me with several different data frames, so I cannot tell where the problem comes from. You could try the example dataset I provide (run data(ecophysio)) and see if it works with the four levels (it should do an ANOVA), and if you remove two of the levels (then it should do a t-test). Let me know if this works as expected!

Cheers
Aitor

**Closed as completed** 2024-05-30 22:31 UTC
